services:                      
    application.file_uploader:
        class: LillydooBundle\Service\FileUploader
        arguments: 
            - '@request_stack'
            - '@doctrine.orm.entity_manager'
            - '@session'
            - '@router'
            - 'lillydoo'
            - 'addressbook_edit'
            - 'documents'
            - 'userfile' 
            - 'description'
            - '%kernel.root_dir%'

