addressbook:
    path:     /
    defaults: { _controller: "LillydooBundle:Addressbook:index" }
    methods:  GET

addressbook_show:
    path:     /{id}/show
    defaults: { _controller: "LillydooBundle:Addressbook:show" }
    methods:  GET

addressbook_new:
    path:     /new
    defaults: { _controller: "LillydooBundle:Addressbook:new" }
    methods:  [GET, POST]

addressbook_create:
    path:     /create
    defaults: { _controller: "LillydooBundle:Addressbook:create" }
    methods:  [POST, PUT, GET] 

addressbook_edit:
    path:     /{id}/edit
    defaults: { _controller: "LillydooBundle:Addressbook:edit" }
    methods:  [GET, POST]

addressbook_update:
    path:     /{id}/update
    defaults: { _controller: "LillydooBundle:Addressbook:update" }
    methods:  [POST, PUT, GET]   
    
addressbook_delete:
    path:     /{id}/delete
    defaults: { _controller: "LillydooBundle:Addressbook:delete" }
    methods:  [POST, DELETE, GET]

addressbook_upload:
    path:     /{id}/upload
    defaults: { _controller: "LillydooBundle:Addressbook:upload" }
    methods:  [POST, PUT, GET]   
    
addressbook_deletedocument:
    path:     /{did}/{id}/deletedocument
    defaults: { _controller: "LillydooBundle:Addressbook:deletedocument" }
    methods:  [POST, PUT, GET]  
    
addressbook_updatedocument:
    path:     /{did}/{id}/updatedocument
    defaults: { _controller: "LillydooBundle:Addressbook:updatedocument" }
    methods:  [POST, PUT, GET]  
    
 
addressbook_search:
    path:     /search
    defaults: { _controller: "LillydooBundle:Addressbook:search" }
    methods:  [POST, GET]  