<?php

namespace LillydooBundle\Repository;

/**
 * AddressbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressbookRepository extends \Doctrine\ORM\EntityRepository
{
}
