<?php

namespace AnomaliesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentsRepository extends EntityRepository
{
    public function getRecords($id)
    {
        return $this->createQueryBuilder('d')
                    ->andWhere('d.user_id = :id')
                    ->andWhere('d.enabled = :enabled')               
                    ->setParameter('id', $id)
                    ->setParameter('enabled', 1)                
                    ->getQuery()->execute();
    }
}
